name: Server

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: |
          mkdir -p $HOME/.local/bin
          curl -svL https://github.com/grpc/grpc-web/releases/download/1.2.1/protoc-gen-grpc-web-1.2.1-linux-x86_64 -o curl -sL https://github.com/grpc/grpc-web/releases/download/1.2.1/protoc-gen-grpc-web-1.2.1-linux-x86_64 -o $HOME/.local/bin/protoc-gen-grpc-web
          chmod +x $HOME/.local/bin/protoc-gen-grpc-web
          npm install

      - name: Generate Proto Code
        run: protoc -Iapi --js_out=import_style=commonjs:src --grpc-web_out=import_style=typescript,mode=grpcwebtext:src api/counter.proto

      - name: Build
        run: npm run build

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: |
            build
